# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoGallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('photographer', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
