# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoGallery', '0002_auto_20170322_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photograph',
            name='img_url',
        ),
        migrations.AddField(
            model_name='photograph',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='image_files'),
        ),
    ]
